language: android
dist: trusty
android:
  components:
  - build-tools-28.0.3
  - android-28
cache:
  directories:
  - "$HOME/android-sdk-dl"
  - "$HOME/android-sdk"
jobs:
  include:
  - stage: lint
    script: "./gradlew lint"
  - stage: test
    script: "./gradlew test"
  - stage: assemble
    script: "./gradlew AssembleRelease"
deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_API_KEY"
  file: app/build/outputs/apk/release/*
  on:
    branch: master
    repo: TP-Foodie/Foodie-Frontend-Mobile
after_success:
- sh ./scripts/set_tags.sh
before_install:
- openssl aes-256-cbc -K $encrypted_49c41553f342_key -iv $encrypted_49c41553f342_iv
  -in keystore.jks.enc -out ./app/keystore.jks -d
