language: android
dist: trusty
android:
  components:
  - build-tools-28.0.3
  - android-28
cache:
  directories:
  - "$HOME/android-sdk-dl"
  - "$HOME/android-sdk"
  - "$HOME/.gradle"
jobs:
  include:
  - stage: lint
    script: "./gradlew lint"
  - stage: test
    script: "./gradlew test"
  - stage: assemble
    script: "./gradlew AssembleRelease"
after_success:
- sh ./scripts/set_tags.sh
before_install:
  - openssl aes-128-cbc -K $enc_keystore_key -iv $enc_keystore_pass -in key.jks.enc -out key.jks -d
deploy:
  provider: releases
  api_key:
    secure: JItMJ0KP1TIZ7UvAmpwalF5vETtgTU+S9vvE9dLMPwtJeGAXQ0vKZ5qPU56f45OinUtit6Q7X7yELShrOgttdeBRiURBb9h9Jw3ieUr+yIQrAir1HSOwG9h4JhtGh8CYHw8Tm622OkjspgSVXCBCBPriaUajmeFhUUJFYGze7vAdyRRW52RgX984krOL/kDGrsSB2grUBm47Z9jbxXNv6S++fbWWiE6HURb1zH+5CKRVfv0iL+YJtVa36BDsvtcaX8hX7p4VRg/1LeDcTvgJSKiIcipF0XQ44YMbR0fyo6FvkWA6lxDqShcikjljvoX5VeZWUduA14HcIowy8WfOn2w7uyP6m/pwQb9JJbwaOtRcI7TIUro6+sKGZCbzmobSHAhgPK5G4onMJfSNKpv0EUrKqnRbIAslDKEjq2N6ePAfs3YVq7CqatEfMq2fWX1N/p1TdPAhJyYh/ZhGHg4wRedV9FOWMV0MZx5EuFQdvWPyDxxwUfQwqpCnbpIvV5wsk5HZYrYAQBv8wRomuE8SSkF7QvDDxFRXjz2p9jcQjWd/YsPATyxYIfjjq7tUVKMgLfMHa2Vh5d/hnNPkMhlH4fa7+qOiOL9Dm8yRRV4ZZifOTlCcqLoXEd6TwJeoSP4xEiWyOTy2oT0ii+N85/yy0/EHb+3izho2w8/V39EmU88=
  file: app/build/outputs/apk/release/*
  file_glob: 'true'
  skip_cleanup: true
  on:
    branch: master
    repo: TP-Foodie/Foodie-Frontend-Mobile
env:
  global:
    secure: j6jayUaoVS8CulLUgozP5EAD8jEa1cvq+K9k/PedlR2EZHeUMFbIYUbCWUaha7E/XigE1Xho+8SdXgj7R0qp/r0sfoByuHABv3ycVU2WcD5Sgn0bV7qenT4Zdz0PJHBAa4GH+HyQOVIXJq1biu9Z1L7Fo4I0A52owqcW5xKACODowQYfeNZ3vTcAGGVSduJHQyneNa2h0weGcY8u0Su8E1BPrvN9hHkenZV8Pw8mR46qmeBXb3OLLFJU0Wt56RCfJWcq4Ty9NJzxPX0toRdNKOCPArKsJWZ7ZLNKXVygg8Nq/h54vCG9wTv4GyBkR+JALZnYsTbbNy4AHmyQygoLBXYzPqD/4/BXsrE/y8UdHcNqPUsQ1/eC9M1ckSLYiGeHLz5y3a2a1XaoTlVN3pfZ9HmHi2Wzj0gnrJl9g2aO5MdGa/onkCPJZQC0mgtL4RoSeygGL5/l8257jPkRtd7ThP7AL/o3QVZXG9CcIhfkRK+u9C8XCmiARgwK0ssfYi3LdF/yLOn+u2BsqZZLVtO+FxyadGt+DgVECcJapGaJR4B0hP1m0C2cA51qhoqjaUrfpcyJgO0eJDALiRPGWlUM3zin0I1U2d9DBD6IG9LaC1+Tkg+M3BoXimn0Phy1gmyZhv5B4q4QWEw3xZIZ+GOy+LFNr67bbBlZTX1ML3ubPNY=
